### ISSUE TITLE
Issue with Model and Dataset Download Links

### ISSUE THREAD

**Issue by Noriko-ztx01** [YCaigogogo/SWAB#1]
Hello,

I hope this message finds you well.

First of all, I must say that your work is truly impressive, and I have been very interested in following it. However, I encountered some issues while trying to access the **model download link**, **dataset download link**, and **ptm_stats**, as these links do not seem to be working properly. On the other hand, **task_relation** and **SWAB_inputs** are accessible without any problems.

Could it be that the links have expired, or might there be another reason for this issue? I would greatly appreciate it if you could provide some guidance or assistance.

**Comment by YCaigogogo** [comment]
Thank you very much for your attention to our work. After our inspection, we found that some of our download links are indeed no longer valid. We will upload the files again and update the download paths. We apologize for any inconvenience caused and appreciate your understanding.

**Comment by YCaigogogo** [comment]
Thank you for your patience. We have updated the download link for the relevant file. Please try downloading it again.
